[project]
name = "SA_WEF_dataset"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "cmcrameri",
    "contextily",
    "esda",
    "fiona",
    "folium>=0.20.0",
    "geopandas",
    "jupyter",
    "libpysal",
    "mapclassify>=2.10.0",
    "matplotlib",
    "netcdf4>=1.7.4",
    "numpy",
    "pandas<3.0.0",
    "pystac>=1.15.1",
    "rasterio",
    "rioxarray>=0.22.0",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.9.0",
    "scipy",
    "seaborn",
    "xarray>=2026.4.0",
]